#pragma once

#define SCREEN_WIDTH 720
#define SCREEN_HEIGHT 720

#define BOARD_WIDTH 10
#define BOARD_HEIGHT 25
#define BOARD_X_OFFSET 5
#define BOARD_SKYLINE 20

#define NUMBER_OF_BRICK_TYPES 7
#define NUMBER_OF_MINOS_IN_BRICK 4
#define BRICK_PIXEL_SIZE 36